---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - libffi-dev
    - libyaml-dev
    - libssl-dev
    - libsasl2-dev
    - libldap2-dev

- name: "create realms user"
  user:
    name: "realms"
    home: "/home/realms"

- name: "create /home/realms/realms-wiki directory"
  file:
    dest: "/home/realms/realms-wiki"
    owner: "realms"
    group: "realms"
    mode: "0755"
    state: "directory"
    seuser: "staff_u"
    serole: "object_r"
    setype: "httpd_sys_content_t"
    selevel: "s0"

- name: "https://github.com/scragg0x/realms-wiki.git"
  git:
    repo: "https://github.com/scragg0x/realms-wiki.git"
    dest: "/home/realms/realms-wiki"
    version: "{{ realms_version }}"
    update: True
    force: False
  sudo_user: "realms"
#  notify:
#    - "reload discourse-unicorn"

- name: "bower install"
  bower: path=/home/realms/realms-app
  sudo_user: "realms"

- name: Install realms in virtualenv
  pip:
    chdir: /home/realms/realms-wiki
    name: .
    editable: True

    virtualenv: /home/realms/venv
    virtualenv_python: python2.7
  sudo_user: "realms"

- name: "install realms-wiki.json"
  template:
    src: "realms-wiki.json.j2"
    dest: "/home/realms/realms-wiki.json"
    owner: "realms"
    group: "realms"
    mode: "0644"

- name: clone wiki repository
  when: realms_wiki_repo
  git:
    remote: "{{ realms_wiki_repo }}"
    dest: "{{ realms_wiki_path }}"
    update: no
    force: no
  sudo_user: "realms"

- name: start realms wiki
  command: /home/realms/venv/bin/realms-wiki restart
  sudo_user: "realms"
